language: c
script: asdf plugin-test oc https://github.com/bartoszmajsak/asdf-oc.git $TRAVIS_BUILD_DIR 'oc version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
  - windows
  